name: Main

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - name: Configure SSH
       run: | 
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/jockep.key
        chmod 600 ~/.ssh/jockep.key
        cat >>~/.ssh/config << END
        Host jockep
          HostName $SSH_HOST
          User jockep_svc
          IdentityFile ~/.ssh/jockep.key
          StrictHostKeyChecking no
        END
       env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
     - name: Upload files
       run: ssh jockep "echo Test"
      
