name: Main

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build
      - name: Tar files
        run: tar -cvf dist.tar ./
      - uses: actions/upload-artifact@v2
        with:
           name: dist
           path: dist.tar
      
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - name: Configure SSH
       run: | 
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/jockep.key
        chmod 600 ~/.ssh/jockep.key
        cat >>~/.ssh/config << END
        Host jockep
          HostName $SSH_HOST
          User jockep_svc
          IdentityFile ~/.ssh/jockep.key
          StrictHostKeyChecking no
        END
       env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
     - uses: actions/download-artifact@v2
       with:
          name: dist
          
     - name: Prepare server
       run: ssh jockep 'rm -rf /srv/jockep && mkdir -p /srv/jockep && chmod -R 700 /srv/jockep'
        
     - name: Upload files
       run: scp dist.tar jockep:/srv/jockep
       
     - name: Extract new files
       run: ssh jockep 'cd /srv/jockep && tar -xvf dist.tar && rm -rf dist.tar'
       
     - name: Restart service
       run: ssh jockep 'systemctl restart jockep'
      
